uploads = []
generated = []

[[outputs]]
id = "jkCe9Jt_H4HASRFm8WyuG"
uri = "file://backups/backup_20260328_012029.json"
type = "unspecified"
title = "Backup do Banco de Dados - 28/03/2026"

[[outputs]]
id = "w-zPNLu2n3zgC7QSHrBww"
uri = "file://studio-layse-duarte.tar.gz"
type = "unspecified"
title = "Studio Layse Duarte — Código Fonte"

[[outputs]]
id = "JJoyQjtnbedEcUyF31RVA"
uri = "file://studio-layse-vercel.tar.gz"
type = "unspecified"
title = "Studio Layse Duarte — Pronto para Vercel"

[[outputs]]
id = "Iar7tqbxPMlsJDx_OCkbx"
uri = "file://studio-layse-completo.tar.gz"
type = "unspecified"
title = "Studio Layse Duarte — Projeto Completo"
